on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n EdisonRegistry -g EdisonRegistryaaba-rg --location "East US 2" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n EdisonRegistry --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n EdisonRegistry --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n EdisonRegistry --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: edisonregistry.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/.github/workflows/test/myapp" -f  ".github/workflows/azure.yml" -t edisonregistry.azurecr.io/edisoncluster1:${{ github.sha }}
        docker push edisonregistry.azurecr.io/edisoncluster1:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_edisoncluster1_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep edisoncluster16572 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace edisoncluster16572`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: edisoncluster16572
        container-registry-url: edisonregistry.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: edisonclustedockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: edisoncluster16572
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          edisonregistry.azurecr.io/edisoncluster1:${{ github.sha }}
        imagepullsecrets: |
          edisonclustedockerauth